### ISSUE TITLE
Add ST toggle to enable / disable nomination history

### ISSUE THREAD

**Issue by bra1n** [bra1n/townsquare#121]

**Comment by nicfreeman1209** [comment]
Might be nice to have a 3rd option: that it exists but gets automatically flushed each night, or perhaps on each dawn.

**Comment by davotronic5000** [comment]
> 
> 
> Might be nice to have a 3rd option: that it exists but gets automatically flushed each night, or perhaps on each dawn.

We can't do this currently because the townsquare has no tracking of the day/night phases, so there is not really anything at the moment to triger the automatic clearing of the vote history.

**Comment by nicfreeman1209** [comment]
Day/night exists: https://github.com/bra1n/townsquare/blob/main/src/components/Menu.vue#L43

**Comment by bra1n** [comment]
Hm, I'd keep it simple for now. An on/off toggle is a lot easier to add to the menu and socket logic than having one with 3 states that does something a bit more complicated on the third state. I'd also not want to add too much game logic to the app, because then it becomes a chore to maintain everything according to the game rules.

**Comment by langford** [comment]
@bra1n I was definitely surprised at the existence and publicly viewable nature of the voting log when playing (and found out about it in my third game :) ). 

For the people asking for the third option, perhaps instead of auto-clearing it, perhaps making it very visible when it exists would work?

 1. Stop players new to clocktower.online from being surprised at records being kept for the players that wouldn't exist from a trustworthy 3rd party in an in-person game
 2. Make people remind the ST to clear it when it hasn't been. 
 3. Maintain your simplicity goal

What could this look like? 

 - A link showing "5 voting log entries" that sends the toggle event. 
 - A link showing the last voting log entry in summary form that sends the toggle event. 
 - A link showing "Last Vote: <11:53> (See More)" that sends the toggle event. 

Are you interested in this as a PR? Another issue?

**Comment by bra1n** [comment]
@langford I like that idea, to show a link to the nomination history somewhere, probably the voting overlay. I'm not sure where it would fix best, though. If you want to work on it, that should be a separate PR. @davotronic5000 is already implementing the ST toggle to disable the nomination history altogether. :smiley:
