### ISSUE TITLE
Feature Request: automate "free" votes for e.g. traveler exile

### ISSUE THREAD

**Issue by nicfreeman1209** [bra1n/townsquare#122]
**Is your feature request related to a problem? Please describe.**
When a traveler is voted on for exile (and other similar situations) all players may vote. Support for doing this could be smoother.

**Describe the solution you'd like**
Functionality for the ST to run a "free" vote in which all players are given the chance to vote. Dead votes would not be removed. The results would not be recorded in the vote history.

It could be implemented as e.g. a tickbox in the same part of the interface as the choice of vote timer.

**Describe alternatives you've considered**
Current system; use the execution voting interface with some manual intervention to change who can/can't vote.

If wanted I might be tempted to have a go at it.

**Comment by bra1n** [comment]
Nominating a traveler will already change the voting behavior in that dead players that don't have a ghost vote can still vote. The nomination history entry will also look different (banishment vs. execution) and ghost votes are never automatically removed by participating in a vote. So I'm not sure I understand what the issue is here?

**Comment by nicfreeman1209** [comment]
Oh - perhaps its cult leader votes and suchlike that I'm remembering here. I'll look again.
