### ISSUE TITLE
Feature Request: Ability to put in roles/reminder tokens that aren't part of the current script

### ISSUE THREAD

**Issue by CreativeMod1** [bra1n/townsquare#132]
**Is your feature request related to a problem? Please describe.**
So, it's more of an idea which'd help sillier games such as when players like to play oops all pithags/philos, the game is generally that you can be any released role, the pain with this though is that as ST you gotta then go through each edition to change everyones role and to put tokens down ect.
This is also something that would help with a certain unreleased role, I'm not sure when said role will be released if at all but it'd still help with it when it does get released. It would also be helpful for said role to have a full list of roles.

The tokens can also be a help for text games, if you upload a gamesave file, you might not have the correct script loaded but you do have the characters put in and you might want to now assign tokens based on the characters you have loaded

**Describe the solution you'd like**
I think something similar to the Traveller tab would be good, the main issue I'd see is that there's lots of characters, so you'd need to have something to organise the characters to make them easier to sort through and have it as a scrollable page.

For the tokens, making it so that if a character is on the grim, regardless of if it's on the script, you should be able to add their tokens to your grim. I am not suggesting being able to add any and all tokens at all times cos that'd be crazy (unless again you wanted to add another tab for it when you open the Token menu)

**Describe alternatives you've considered**
Not sure

**Additional context**
Personally this'd also be very helpful whenever I'm running a text game too because I tend to just copy over the gamestate jsons and not bother inputting the edition json, so it'd be helpful to be able to change characters/move tokens without having to find the edition json (which in a text game, it might've been weeks ago that I downloaded the json and so gotta hunt and find it)

**Comment by bra1n** [comment]
Thanks for the ticket, @CreativeMod1! Unfortunately, I don't think such a feature would be of much use beyond these very special custom scripts. And for those, I'd suggest that you simply create a custom script JSON that includes every released (and unreleased) role. The grimoire and all the features in it are not built to support scripts that have hundreds of available characters, reminders, etc. so I don't think it would be time well spent to make it work here. Concerning the reminder tokens, you could also fork this project and edit the roles.json to make every reminder token "global", so that it shows up even when the character it's coming from is not assigned to any player.
