### ISSUE TITLE
Bug: Players shifting in townsquare without moving assigned roles

### ISSUE THREAD

**Issue by davotronic5000** [bra1n/townsquare#135]
**Describe the bug**
Reported by @Blackrock on discord https://discord.com/channels/569683781800296501/815378026187587645/821488718401110077
If a player is removed from the townsquare after roles are assigned or notes are taken (possibly a traveler), the remaining players are redistributed in the circle but the assigned roles will not be shifted to match.

**To Reproduce**
1. ST: Host a game with 7 players
2. Player: Join the game and claim seat 5
3. ST: Assign seat 5 any role (e.g. Shabaloth) and click Send Characters
4. ST: Remove seat 2
5. Player: Observe Grimoire

**Expected behavior**
Roles should continue to be assigned to the correct player

**Screenshots**
![image](https://user-images.githubusercontent.com/851576/111380199-f3025000-869b-11eb-9fe5-cea7a3f8c9b9.png)

**Comment by nicfreeman1209** [comment]
I had noticed this too & planned to have a go at it. Without checking code it's something like: the tool (as non-ST, but perhaps also as ST) associates the reminder tokens to positions on the grim (like hour labels on a clock) rather than to the player names. Happy if someone else gets there first though.

**Comment by bra1n** [comment]
The issue was caused by me being lazy when writing the socket code... when the ST removed a player, what happened until very recently was, that the whole gamestate would be sent to every player. Now the player client didn't know which player was removed from the circle, so they simply compared the number of players on the ST side and then removed players from the end of the list until the numbers matched, followed by renaming every player in the circle appropriately. This caused the roles and reminders to shift... I'm surprised, this wasn't caught earlier. :grimacing:
