### ISSUE TITLE
Feature Request: Remember pronouns

### ISSUE THREAD

**Issue by JamesParrish** [bra1n/townsquare#155]
The pronouns feature is great, but it could be improved by remembering a user's entered pronouns and automatically entering them when they sit down in subsequent games. This would make it more convenient for people to use, and would probably result in more people using it.

This could be done by storing a cookie or some browser storage, for example.

**Comment by bra1n** [comment]
I guess I can attach the pronouns parameter to the claiming a seat action so it will remember it from the last time you set it as a player.

**Comment by nicfreeman1209** [comment]
small bug to attach in here: pronouns aren't removed when a seat is vacated

**Comment by bra1n** [comment]
Which is fine, IMO, because pronouns are attached to the player (name)
instead of the claimed seat.

**Comment by nicfreeman1209** [comment]
ok, but they aren't removed by a rename either

**Comment by teenunicorn** [comment]
Small feature request: could pronouns be displayed next to the name, instead of as a tool tip?

I would be happy to submit a pull request for this, and don't mind poking around in the code for the place to fix it.

The reason for this request is that it's somewhat awkward to have to hover over the symbol (and honestly, the first time I saw it, I had no idea what male/female had to do with anything).

I'd also be happy to work on adding a cookie for this.

**Comment by bra1n** [comment]
> Small feature request: could pronouns be displayed next to the name, instead of as a tool tip?

Unfortunately, I don't think this is doable. The space for the name is already very small and longer names usually get cut off. Having the pronouns visible in the same space as the name would add an extra 7-8 characters (at least) to it, which would either cause most names to be truncated after a couple of characters already or hide the pronouns for most of the players anyway due to lack of space.

That said, persisting pronouns is something that will be added to the official app, but not this one.
