### ISSUE TITLE
Feature Request: Custom Jinxes

### ISSUE THREAD

**Issue by Bakedman** [bra1n/townsquare#192]
Simply asking for the ability to implement custom jinxes in jsons that can be used in the web tool. Not entirely savvy on the matter but am aware that doing so is apparently not currently possible and it would be a nice feature.

**Comment by bra1n** [comment]
Hm, not sure I follow. If you create a custom script with homebrew characters, why not just write those characters in a way that there is no Jinx necessary for the interaction with other roles on that homebrew script?
And if it is about two non-homebrew roles being jinxed, then the official list of jinxes should be all that's necessary.

**Comment by Bakedman** [comment]
For example, the way that vortox interacts with misregistering can be inconvenient for some custom script. One particular example i can think of is how it interacts with fortune teller. The ability to make a jinx where the fortune teller's red herring registers as not a demon in a vortox game would be nice.

**Comment by bra1n** [comment]
That would no longer match what the offiicial Fortune Teller / Vortox interaction is, so at that point it would be better to either make a homebrew FT or a homebrew Vortox with an adjusted ability, rather than adding an unofficial jinx.

**Comment by JulGvoz** [comment]
> Hm, not sure I follow. If you create a custom script with homebrew characters, why not just write those characters in a way that there is no Jinx necessary for the interaction with other roles on that homebrew script?
> And if it is about two non-homebrew roles being jinxed, then the official list of jinxes should be all that's necessary.

There is a use case for homebrew rulings, and attempting to reword existing characters to fit those rulings is near-impossible.

Similarly, wording the homebrew abilities to interact with each other in intended ways is also near impossible, since, if one also intends to fit the homebrew characters on a PDF sheet, the length of the ability text is constrained.

Furthermore, while it isn't done usually, there may come a time where players will start to mix-n-match homebrew scripts, similarly to how we construct custom scripts currently. Allowing for jinxes between characters not in original script (similar to the way official characters does it) would allow such a future use. And, if it seems like "we'll cross that bridge when we come to it", I think that most homebrew is encouraged by the fact that the clocktower townsquare tool allows for it (for example, people seldom put custom fabled before the tool allowed it, yet now nearly everyone does it).

Finally, there is merit in restructuring the existing roles. While, by my understanding, the current `hatred.json` file is simply fetched from https://bloodontheclocktower.com/script/ website, the file uses character names, instead of character ids. If jinx information was instead stored in `roles.json`, the actual role and its jinxes would be in one convenient place.

**Comment by bra1n** [comment]
The thing is, jinxes and roles are structured very differently, so it wouldn't make sense to merge these two datasets into one file. Currently, they are also not fetched from bloodontheclocktower.com, because their server doesn't send CORS headers, so I have to keep a local copy in https://github.com/bra1n/townsquare/blob/develop/src/hatred.json
Of course, if we add such a feature, people are going to use it for their homebrew - but that would be true for almost any kind of feature we'd add. And given that, I think that the demand / need for custom jinxes is very low right now. I don't think it's never going to happen, but for now if you really want to play with your own set of homebrew jinxes, I'd suggest you fork the source code and adjust the above mentioned hatred.json to your liking.
