### ISSUE TITLE
Feature Request: Automatically change night order numbers during a game if a player dies

### ISSUE THREAD

**Issue by Malvora1845** [bra1n/townsquare#208]
This isn't really a huge issue, but I find I occasionally struggle to find who I need to wake next during the night after a couple of people have died. For example: The Poisoner (1), Monk (2), and Imp (3) are still alive, but I then have to either go through the dead people to find out the Empath (4) and Fortune Teller (5) are dead or realize that the living player with the lowest night order number left is the Butler (6) before I can actually wake them.

I think it would generally improve the overall QoL for Storytellers as well as speed up the night phase if night order numbers automatically updated once a player has died, similarly to how they only count in-play characters when assigned, so you don't have to go searching for the next lowest number.

Another thing that's somewhat related would be to have characters that still act when dead (like the Zombuul) maintain their night order number even if dead, and also to have it still be in color instead of greyed out.

**Comment by bra1n** [comment]
Hey @Malvora1845,

what you described was already how the night order initially worked - dead players were not considered for the night order numbers anymore. However, after gathering some feedback from the community, the majority of players preferred to have the night order still count for dead players too, which is why this is how it is implemented now. This also "fixes" the problem with dead roles still having an ability (eg. through Zombuul or Bone Collector), so I'm not going to change this back.

Alternatively, you could also use the Night Order screen (press "N" to open) and go from top to bottom there, skipping players whose name has been crossed out.

**Comment by Malvora1845** [comment]
Ah, I wasn't aware of that, didn't expect the way it is now to be widely preferred. Thanks for letting me know!
