### ISSUE TITLE
Clarify "number of votes required for execution" text on voting screen

### ISSUE THREAD

**Issue by davotronic5000** [bra1n/townsquare#24]
On any votes after the first in a game day, the number of votes required to succeed is incorrectly shown based on previous successful votes.  It curently always shows the number purely based on the number of alive players.

**Comment by bra1n** [comment]
Hi Dave, I agree that this might be a bit confusing. Maybe I'll change the wording to "_minimum_ number of votes required for execution" or add a way for the ST to set this number. What I can't do is update this number based on previous nominations. This projects intentionally does not implement specific role abilities in order to keep it maintainable and easily extendable and due to that, there is no way I could calculate actual votes received, when there are roles like the Bureaucrat or the Thief.
That said, I'll add an item to the todo list to clarify the wording a bit so that there is less confusion.

**Comment by davotronic5000** [comment]
Great, I appreciate some of the roles make it difficult to know if a vote passed or not, the option for allowing the ST to modify the number of votes required would work well.

**Comment by JamesParrish** [comment]
An idea for this coud be to have the "X votes required" automatically be set to one higher than the number of votes on the previous nomination, then give the storyteller a "Reset votes" button that resets the number to the value based on alive people remaining.

**Comment by bra1n** [comment]
That would also require keeping track of votes across multiple "rounds", which is something I don't want to add for now. It would also require quite a lot of work under the hood with live sessions.

**Comment by bra1n** [comment]
The text now says "X votes required for a majority", which is more correct and should be less confusing.
