### ISSUE TITLE
Feature Request: Show your own role in your "personal" Grimoire

### ISSUE THREAD

**Issue by unrealed** [bra1n/townsquare#25]
It would be nice if the Grimoire that you can show for yourself had your role above your name. It would clarify what that screen is for immediately and would save time during setup by not making the Storyteller tell everyone manually what each player's role is in a DM. Ideally, you could still replace it with other stuff in case you think you're actually a Drunk or a Lunatic (but then it should also let you "reset" to the role that was shown to you)

**Comment by bra1n** [comment]
Hi Ed, that feature would mean the Storyteller has to send secret information through a live session, which is happening with plain text socket messages right now and can be read by anyone in the session with some technical expertise. I want to keep the live session part as lightweight as possible for now, so you still need some other means of (private) communication with your players in order to send them their role.
