### ISSUE TITLE
Feature Request: a feature idea.

### ISSUE THREAD

**Issue by sad912** [bra1n/townsquare#257]
I am glad to play this game with friends by your open source project. In live game. we must need the storyteller to continue the process, but in online one, can u provide a option to the auto-storyteller which will increase efficiency of the game? Thanks again for your open source project.

**Comment by bra1n** [comment]
Hi @sad912,
thanks for your suggestion! In Blood on the Clocktower, the Storyteller is an integral part of the game, very much like the players. And replacing them with some kind of AI would only work as good as replacing a player with an AI. They have to make informed decisions to keep the game balanced and some character abilities would be outright impossible with a computer Storyteller. On top of that, the authors of the game (TPI) have asked their fans specifically to not create some kind of automated Storyteller app - because it would lead to a poor game play experience in most cases.
