### ISSUE TITLE
Request: remove mark for execution after player dies

### ISSUE THREAD

**Issue by Urganot** [bra1n/townsquare#266]
**Describe the bug**
The marked for execution marker stays on the player even after the shroud token is set.

**To Reproduce**
1. Start a vote
2. after voting click "Mark for execution"
3. Close voting
4. Click on marked players shroud token
5. Mark stays

**Expected behavior**
After killing a player, the mark should be removed 

**Screenshots**
![image](https://user-images.githubusercontent.com/5991022/175792033-af39b4b8-1b87-45f7-acc8-17003da3e3e1.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome 102.0.5005.115

**Comment by bra1n** [comment]
Thanks for the ticket, @Urganot! This isn't really a bug, but more of a feature request. The mark for execution is removed, when the Storyteller switches to the night phase - which makes more sense, since some roles can't die during an execution or the marked player might already be dead, for example. I guess it could also be cleared when the marked player dies, but given that the very next thing to happen is the beginning of the night, it seems somewhat redundant.

**Comment by Urganot** [comment]
I didnt know that. We dont use night mode most of the time. Thanks
