### ISSUE TITLE
Bug: Majority should be calculated without tavellers

### ISSUE THREAD

**Issue by Urganot** [bra1n/townsquare#267]
**Describe the bug**
When playing with travellers, during voting, the message (majority is X) should not include travellers in its calculation

**To Reproduce**
1. Start a game with 8 players
2. Add one or two travellers
3. start a vote
4. Message says (Majority is 5) 

**Expected behavior**
Message should say (Majority is 4) because there are 8 alive non traveller players.

**Desktop (please complete the following information):**
- OS: Windows 10
- Browser: Chrome 102.0.5005.115

**Comment by bra1n** [comment]
I think you've got a rule wrong there. 🙂 Travellers *are* included in the calculation for whether a vote passes or fails: 
![image](https://user-images.githubusercontent.com/325521/175827005-da6b51cd-734c-488a-8248-d1e59ec3ae3f.png)
In fact, travellers only have 2 differences during the game: they don't count against the Evil team win condition and the are exiled rather than executed. Apart from that, they're the same as any other player.
