### ISSUE TITLE
Feature Request: Flipping menus/tooltips that appear outside the screen

### ISSUE THREAD

**Issue by unrealed** [bra1n/townsquare#28]
When you have your window scaled in a more vertical manner (like if it's split over half your screen) then some menus or tooltips can appear outside of the screen. Clicking the name of the players on the right means you don't see the entire (or any) of the menu that appears there. And this can also happen both on the right AND left for the Grimoire tooltips (either for role description or night order tooltips)

Having menus/tooltips appear on the other side if they're from the more side-located roles would fix this issue

**Comment by bra1n** [comment]
Yeah, this has also been bugging me, but I haven't found an easy solution for that yet. The same happens on small screens with the player menu getting cut off at the top of the screen. I'll see if I can find a fix.

**Comment by unrealed** [comment]
Maybe the solution is just making all tooltips appear in the middle of the screen. Means you don't have to have any fancy scripting, and things will always look neat

**Comment by bra1n** [comment]
I moved the player menus to always open inside the player circle, this should at least fix the issue of inaccessible player menus.
Generally speaking, there is no easy way to keep tooltips inside the window and I'd rather not move them to the center, because they'd lose their visual connection to whatever you're hovering. I guess it's just a drawback of playing in "portrait mode."
