### ISSUE TITLE
Feature Request: Blue is too close to cyan

### ISSUE THREAD

**Issue by jimr1603** [bra1n/townsquare#296]
**Is your feature request related to a problem? Please describe.**

I find the blue tokens (villages) too close to the cyan tokens (outsiders). 

**Describe the solution you'd like**

A bigger difference between the blue for villages and the cyan for outsiders. 
Consider also running the system through some colour-blind simulators to check everything's good for different types of colour-blindness.

**Comment by bra1n** [comment]
Hey James,
what exactly do you mean when you're talking about the townsfolk and outsider colors? The icons on these tokens should all be the same shade of blue, while the outlines are mostly just there because the app always had them. Originally, there shouldn't even be a color difference between Outsiders and Townsfolk (or Demons and Minions, for that matter), because color only denotes the side you're playing on (Good vs. Evil), but not the character "type".

**Comment by jimr1603** [comment]
Hi Steffen,

Hoping that reply from email works here.

Screencap from the game:

[image: image.png]

The Outsiders have a cyan outline on the token, the townsfolk a blue
outline. I ended up claiming the moonchild was a townsfolk.
Compare with the orange/red that's pretty clearly different between the
demon and the minions

--James
