### ISSUE TITLE
Allow custom editions with custom characters

### ISSUE THREAD

**Issue by atalekar** [bra1n/townsquare#4]
Love your tool  - this is awesome. But in recent months our game play has evolved and we have created quite a few custom scripts. 

I was wondering if your tool can be extended to add custom roles ? (ie edit names on some generic tokens when set is 'custom'). Thanks!

**Comment by bra1n** [comment]
So, I got two ideas in this regard:
- allow the use of custom scripts that have been generated with [the Script tool](https://bloodontheclocktower.com/script-tool/). This would be as simple as exporting your custom set from the tool to JSON and then importing that JSON on the Town Square. I'll probably implement that soon-ish.
- allow the use of custom *editions*, including custom token images. This is a bit more work and would require you to basically write your own [role.json](https://raw.githubusercontent.com/bra1n/townsquare/master/src/roles.json) definition. You can already start with that, the structure should be self-explanatory. The `firstNight` and `otherNight` fields are the order in which the characters wake up on the first night / other nights. For custom scripts, there will be an additional field called `image` (or something like that) that has to be a URL to an image of the token icon on the net. 
Would you have time to write down such a roles.json for one of your custom scripts so that I can test it?

**Comment by verballyinsane** [comment]
I would love to see a "No Script" option as well, for using it just as a town square with custom editions.

**Comment by bra1n** [comment]
> I would love to see a "No Script" option as well, for using it just as a town square with custom editions.

I'm not sure I understand what you mean. Using just the town square without any character tokens is totally possible right now. You'd just add the players and then toggle their status (alive / dead / no vote) by clicking on the town square tokens. Or what did you mean?

**Comment by atalekar** [comment]
Townsfolk / Outsider character can have a generic blue background, and editable text. 
Minion / Demon characters can have generic red background, and editable text.
Travelers can have a generic blue/red or just green background, with editable text.

**Comment by bra1n** [comment]
> Townsfolk / Outsider character can have a generic blue background, and editable text.
> Minion / Demon characters can have generic red background, and editable text.
> Travelers can have a generic blue/red or just green background, with editable text.

There isn't going to be an edit mode on the page, because that would be a huge undertaking with little to no gain. If you want to create a custom set, just edit the roles.json like I've mentioned before: https://raw.githubusercontent.com/bra1n/townsquare/master/src/roles.json
Everything else will be handled by the website automatically. :) You can even provide new icons, if you want!

**Comment by bra1n** [comment]
> So, I got two ideas in this regard:
> 
> * allow the use of custom scripts that have been generated with [the Script tool](https://bloodontheclocktower.com/script-tool/). This would be as simple as exporting your custom set from the tool to JSON and then importing that JSON on the Town Square. I'll probably implement that soon-ish.

This has been added now and is available for use. :-)

**Comment by bra1n** [comment]
Support for custom characters has arrived: https://github.com/bra1n/townsquare#custom-characters
