### ISSUE TITLE
Feature Request: Add pronoun flags 

### ISSUE THREAD

**Issue by Julzerator** [bra1n/townsquare#43]
**Is your feature request related to a problem? Please describe.**
There are many players in the community that sound different to the pronouns they prefer. I would love to have a way for my players to, when they take the seat, be able to highlight their preferred pronouns. `she/her` `they/them` `he/him`

**Describe the solution you'd like**
The storyteller sets up the grimoire with who is playing with their names. When players log in to session and choose their seat, they have the option to select a pronoun flag that appears under their name.

**Describe alternatives you've considered**
As a storyteller we can always add this to their player names, but when playing with new friends we might not always know what pronouns they prefer to type them in. This would allow the players themselves to have control over the sharing of this information.

**Additional context**
n/a

**Comment by bra1n** [comment]
Hey @Julzerator,

thanks for the detailed ticket description! I agree that this would be a useful feature, however I think it is also pretty low on my todo list, since there are already ways to convey this info through other means. (and you can't really play BOTC with my townsquare website alone - you need a voice chat anyway) I'm open to PRs however, so if you want to take a stab at it, feel free to! :-)

**Comment by Julzerator** [comment]
I will try to put something together. It's been a while since I did anything front end.

**Comment by cyyfyy** [comment]
@Julzerator still workin on this?  If not, I may give it a go myself.

**Comment by bra1n** [comment]
I would have some time now to work on this, however I'm not sure how to best visualize a preferred pronoun. Any design ideas? Keep in mind that information space around the player tokens is already scarce and that the design needs to work on both big screens and small screens with reduced font size.

**Comment by davotronic5000** [comment]
I think because of the limited amount of free space in the town square, this could be added as a tooltip on the players name, similar to how abilities are displayed on tokens now.

If no one else is working on this currently, I can take a crack at it, also if anyone has any better ideas for presentation.

**Comment by bra1n** [comment]
That's actually a pretty good idea! I'll keep it in mind when I get back to this ticket, unless someone beats me to it. 😁
