### ISSUE TITLE
All travelers selectable

### ISSUE THREAD

**Issue by unrealed** [bra1n/townsquare#52]
It would be great to have the option to select all Travelers regardless of the edition/script selected, since choosing any Traveler you want is a 

The easy way for you to implement this is adding the roles to the list of roles for each edition.
The BETTER way to do it imo would be to have a 2nd screen which lets us select Travelers from the whole list of Travelers. I imagine a button called "Travelers" that rotates the menu, like the button that rotates between the Reference sheet and the Night Order sheet (tho, imo, the button itself should read "Travelers" instead of having a little symbol like the Night Order sheet button does)

**Comment by bra1n** [comment]
I'm not a fan of that idea, for a few reasons:
right now there are 15 travelers, but with new sets there will be even more and having all of them selectable at the same time will quickly drown out any other roles. I also don't want to separate them into their own list for now, because they're player roles as much as townsfolk or minions are.
The other reason is, that each of the base 3 sets has 5 travelers that are primarily tailored to this set, so you *will* run into problems if you use travelers from other sets. (like Judge in TB, for example) Custom scripts can (and do) provide their own selections of travelers, so if you're playing a custom script and want to see specific travelers on the list of roles, just tell the script author to add those travelers to the script. If you want travelers from different sets in your base 3 game, just switch the edition, add the traveler and then switch back.

**Comment by unrealed** [comment]
I don't agree with your first counter point, because, yes they will add more , but we can probably expect a rate of 5 per extra editions, and we know there are only 3 of those coming for a while (+ Greatest show on earth, but that one's different). Also, yes they are player roles as much the others, but if you make the button to access this Travelers menu visible, then Storytellers won't miss it.

For the second counter point, you could re-use the layout you have for selecting & assigning roles where each row is a different type. The only difference is you'd add the edition's logos/names to the left of each row to make it clear which Travelers fit which edition. While yes you CAN create bad Travelers choices, it's still something that's possible to do today, just more annoying. And if you're that concerned about selecting "wrong" Travelers, you could add text above the menu warning Storytellers, or add a pop-up warning when selecting one. 

Now I think about it, it'd be best, imo, to have both the travelers for that edition/script displayed as they are currently AS WELL AS having this secondary menu that shows all Travelers. That way the suggestion of which Travelers to use is even stronger because you only see the "right" ones by default, but CAN go fetch the others if you want. But currently, if you're an experienced ST and want to use a specific Traveler but don't know the app quite well, you might think it's not possible to use out-of-edition Travelers, and that is IMO a UX failure

**Comment by bra1n** [comment]
That's fair, I'll see what I can do. :-)

**Comment by JulGvoz** [comment]
Is it possible to instead set a player to a Traveler type, and then allow the ST to choose a traveler from there?

**Comment by bra1n** [comment]
This is currently being worked on by someone else, with the idea of using tabs for the different teams (townsfolk, outsider, minion, demon, traveler), thereby creating enough space to show additional / all travelers on demand.

**Comment by bra1n** [comment]
Done, thanks to @davotronic5000.
Added with 2.5.0
