### ISSUE TITLE
Bug: Votes displayed incorrectly

### ISSUE THREAD

**Issue by Duckheady** [bra1n/townsquare#57]
There have been several times I have seen the issue, and glancing at the code it seems that it is just a failure to account for inherent network lag. Essentially the problem is that if a vote is submitted at the last second on client side, the client can register that they voted yes, but other players see a No (or vice-versa.)

Reproduce steps (not consistent pointing toward network latency even more):
1. Start execution vote.
2. Begin votes.
3. Right before the clock hand locks in, switch your vote.
4. If the bug occurs, there should be a desync between clients.
(May want to test with fake latency injection code to identify)

Fix: I would suggest a handshake system or server side grace period that favors the voter so even if there is a slight desync it should update the vote on the other clients before the next person votes while not confusing the voter.

Good Luck,
Duckheady

**Comment by bra1n** [comment]
Hi Duckheady,

thanks for your ticket! Everything related to live sessions is currently handled with websockets, an asynchronous protocol by design. This means that handling lag is basically not possible, any delay I would add between the host "locking" a vote and the client still being able to change their vote would be artificial and not handle the underlying problem when someone has a bad connection. It might make the "experience" of voting at the last second a bit more smoothly, but then again, in a real life game of BOTC, if the Storyteller has pointed at you, it's too late to change your vote.

What should *not* happen is the your player client and all other clients / the host disagreeing on whether you voted yes or no. The host will always send the locked in vote value (true/false) along with the locking countdown, so any connected player, including yourself, should the same vote result. If that's not the case, please reopen the ticket.

Changing the session mechanism from asynchronous to something synchronous that is able to do handshakes and handle lag would be way beyond the amount of time I can currently dedicate to this project. If you want to give it a try yourself, feel free - I'm open to any and all PRs. :-)
