### ISSUE TITLE
Bug: Custom scripts using homebrew characters allow arbitrary links for the image.

### ISSUE THREAD

**Issue by JulGvoz** [bra1n/townsquare#60]
**Describe the bug**
![image](https://user-images.githubusercontent.com/46909274/95555499-90d15f00-0a1a-11eb-9d94-bae751f5c15f.png)

**To Reproduce**
1. Create a custom image which collects IP addresses with a custom domain
2. Create a script with homebrew character, and attach the image to the character.
3. Hosting a game with that script will now allow collection of player IPs

**Expected behavior**
External images should only be downloaded from trusted sources, or players should be able to disable external images

**Screenshots**
![image](https://user-images.githubusercontent.com/46909274/95555962-37b5fb00-0a1b-11eb-94e4-05cbad061a41.png)

**Comment by bra1n** [comment]
This will be fixed in v2.0, where custom roles are no longer loaded through live sessions. Instead, if you want to play with custom roles each player has to manually load the JSON file, where I added a warning to only load files from trusted sources.
This has the nice side-effect that my server no longer has to pass hundreds of kilobytes to each player in a custom edition live session.
