### ISSUE TITLE
Feature Request: Time and History Tracking

### ISSUE THREAD

**Issue by pinual** [bra1n/townsquare#62]
**Is your feature request related to a problem? Please describe.**
I have been running games for my group for a few months now and this app has been very helpful for some of the work involved however there are still things I need to track outside the app.  Most important being Time and History.  Our group really like to consider opinions and discuss which takes up a lot of time so they need to be cut off.  I need to track time before nominations are open, after they are open, and time spent on each nomination, so that I can make sure it does not run for too long.  I also need to track who nominated who so it cannot be repeated which an can be difficult in big games.  I try to track votes as a verification for Flower Girl or Town Crier, but also use it sometimes for Savant info.

**Describe the solution you'd like**
I'd like to see a timer in the UI that is only visible to the host.  That timer could be broken into over all game time, time this day, and time on segment (before/after nominations open and time on nomination).  Then the history could get appended to an event log which is also only visible to the host.  It need only say who nominated who and then who voted.  For example:
Bob nominated Alice: (4) Bob, Claire, Erin, Steve.  Success or failure is not really needed and can be figured out from the info but just having the log would be very helpful.

**Describe alternatives you've considered**
I get that the timer may not really be a necessity as other storytellers may be more naturally adept at sensing the passage of time but I would really like to get a simple log of nominations and results.  I wrote my own app for tracking the information but it's fairly primitive and it is a pain to try and manage both when the information is readily available in this app.  Here is a screenshot of what it looks like.  It has a term "whispers" we use in our game meaning the time when people may chat in private.  But just an example of the kind of info I am wanting to track.
![image](https://user-images.githubusercontent.com/35266072/97785668-e661dd00-1b7c-11eb-9832-cd99c742dad7.png)

**Additional context**
In the end I'd like this app to be the one tool to rule them all.  The exception being a voice tool for online play but otherwise in person, I'd like for this app to track everything I need.

**Comment by bra1n** [comment]
Thanks for the detailed suggestion, @pinual!
I think the tool you built looks really useful and I also agree that having a history of nominations / vote results would be useful. I added that to the todo list already and I hope to find some time to implement it somewhat soon. 
That said, I think there are limits to what this town square should be able to do and not do. For example, I would never add a voice chat feature to the page, because that would be a huge undertaking and never as good as already existing solutions. In a similar vein, I think adding too much game logic to the tool, like tracking day/night phases, public timers, etc. would turn it from a Storyteller tool to basically a game engine, and for now I would prefer to keep it as close to a real grimoire / town square as possible.
You also have to keep in mind that there are already a plethora of other features implemented that make the grimoire somewhat hard to use, so at some point I also have to weigh added complexity against usefulness of every new feature I build. I'm not sure that what you suggested would be useful enough when most Storytellers are probably already using their computer clocks or smartphone timers for this. I plan to do the vote history though, if that's any consolation. :-)

**Comment by pinual** [comment]
Thanks @bra1n - I figured the timer was a longshot.  I have actually not had any issues personally with the complexity of the app.  I think you designed it so that it is mostly intuitive.  Adding timers and buttons for management would certainly make it complicated.  I appreciate your consideration of the nominations and vote history.

**Comment by bra1n** [comment]
Nomination and vote history has been added now, as well as a night phase toggle. I'm aware that those are not timed, but then again, the game doesn't aim to be timed down to the second, so I'd suggest just using an external app if you need to track individual phase times. ;-)

**Comment by pinual** [comment]
Thank you @bra1n for adding the history feature.  It will be very helpful for tracking what happened.  Some in my group however do not want that information available to players, just the StoryTeller, so I've been trying to remember to clear it out at the end of the day.  We love the night phase toggle!
