### ISSUE TITLE
Text boxes sometimes blurry

### ISSUE THREAD

**Issue by daalta** [bra1n/townsquare#7]
# In Chrome and Firefox:
* Some text boxes for characters descriptions are blurry.

Normal text box:
![2020-05-08_12-32-40](https://user-images.githubusercontent.com/9169275/81397638-0497d480-9128-11ea-8ba6-670a329feb87.png)

Blurry text box:
![chrome_2020-05-08_12-32-27](https://user-images.githubusercontent.com/9169275/81397641-05c90180-9128-11ea-85f6-cf59d40d9947.png)

# Firefox only:

* Names are sometimes blurry
* First night / other night texts blurry and aliased

![firefox_2020-05-08_12-37-32](https://user-images.githubusercontent.com/9169275/81398056-c949d580-9128-11ea-82c9-e133a0ad0b35.png)

![2020-05-08_12-39-38](https://user-images.githubusercontent.com/9169275/81398203-0ada8080-9129-11ea-9e91-7a63515c4df9.jpg)

**Comment by bra1n** [comment]
Yeah, this is a by-product of arranging elements in a circle with `transform: rotate()`. Not sure if there's anything I can do about it, but I'll look around a bit.

**Comment by bra1n** [comment]
Alright, I searched for a fix and it seems like I can always only fix *some* of the blurry text boxes, while others will stay or become blurry in the process. The way Chrome (and Firefox) handles rotated elements unfortunately leads to blurry text some of the time and given that there are many different positions and rotations, there is no way to fix all of them at the same time.
Maybe this will be fixed in the browser engine at some point, but as it is, I can't fix it here for now.
