### ISSUE TITLE
Feature request: custom role icons / custom script logo

### ISSUE THREAD

**Issue by davotronic5000** [bra1n/townsquare#74]
I think there are a couple of graphical bugs with the custom character support in scripts.

The first is custom token images to not appear to resize correctly for the player tokens, but are fine for reminder tokens.
![image](https://user-images.githubusercontent.com/851576/103011452-dab5e580-4531-11eb-91dd-852e4eec15de.png)
If it helps the images I have been working with are https://raw.githubusercontent.com/davotronic5000/ChristmasBrewing/main/Santa-Sack.png?raw=true and https://raw.githubusercontent.com/davotronic5000/ChristmasBrewing/main/Grinch.png?raw=true.  It might just be that there are some sizing requirements needed for the images used.

The second is if a json file is uploaded by a player that includes a custom logo, it displays correctly, but if you then join a STs session running the same script the custom logo is replaced with the default "Custom Script" logo.

**Comment by bra1n** [comment]
Hi Dave,
concerning the token icons: your images need to be square (the santa-sack.png is 138x169 for example) and need to take the padding on the sides of the token into account. Take a look at the Butler icon: https://github.com/bra1n/townsquare/blob/main/src/assets/icons/butler.png
If you highlight the image, you can see that there is plenty of empty space around it, to make it look good on the token:
![Bildschirmfoto 2020-12-23 um 19 38 30](https://user-images.githubusercontent.com/325521/103027648-8b35e080-4556-11eb-98bb-b8c8de65cb32.png)
Your custom icons need to do the same to look good.

Second, custom script logos are currently not supported in live sessions, because players currently can't control what the Storyteller might load as an image. As soon as I've implemented a toggle for this, it will be possible to show the logo in live sessions too, assuming the players have enabled custom image support in their Grimoire. :-)
