### ISSUE TITLE
Bug: Fortune Teller Role Night Order

### ISSUE THREAD

**Issue by nivek1385** [bra1n/townsquare#78]
**Describe the bug**
The Fortune Teller at the beginning of the game shows that the Fortune Teller goes first during both the First Night and Other Nights.

**To Reproduce**
When starting a game as the Fortune Teller, the interface has the 1s on both sides indicating that the Fortune Teller goes first during the First Night and Other Nights. The number shouldn't be a 1 as the Fortune Teller doesn't go first during the nights. 

**Expected behavior**
It either doesn't show a 1 or put an asterisk if it's meaning of the roles set in the player's Grimoire, the role goes first.

**Screenshots**
None available

**Desktop (please complete the following information):**
OS: Linux Mint 18.3
Browser: Brave
Version 1.18.70 Chromium: 87.0.4280.101 (Official Build) (64-bit)

**Comment by bra1n** [comment]
Hi @nivek1385,
I can't reproduce this issue. Both the numbers on the token as well as the place in the night order screen are correct for me:
![Bildschirmfoto 2021-01-01 um 13 52 00](https://user-images.githubusercontent.com/325521/103438909-8ea52800-4c38-11eb-8eef-2f48a8656293.png)
![Bildschirmfoto 2021-01-01 um 13 52 23](https://user-images.githubusercontent.com/325521/103438911-9795f980-4c38-11eb-92db-5cd25e1be57d.png)
Keep in mind that the token numbers only show you the position of the Fortune Teller in the night with the current selection of characters. Maybe you didn't assign any other characters yet?
Please provide a screenshot of the whole Grimoire or a JSON game state export (menu -> Help/Question mark -> Game State JSON) so that I can reproduce it. Thanks!
