### ISSUE TITLE
Feature Request: round timers

### ISSUE THREAD

**Issue by Thomas-Hirsch** [bra1n/townsquare#79]
While it can be fun having several rounds of people having private conversations to plot/scheme/compare notes during rounds, it can be frustrating when the storyteller wants to progress the game to the nomination phase. It would be useful if the storyteller could broadcast a timer to limit the length of the rounds, so after 5 minutes everyone must return to the town square to do nominations/voting

**Comment by bra1n** [comment]
Hi @Thomas-Hirsch, thanks for your suggestion! This has been brought up before: https://github.com/bra1n/townsquare/issues/62
I still feel like timers are something that should be handled by the storyteller and communicated through whatever means you use for talking with each other, rather than being part of the tool.

**Comment by bra1n** [comment]
After talking to TPI, this is something that should not be in the app, for now.
