### ISSUE TITLE
Feature Request: Separate days more clearly on Vote History

### ISSUE THREAD

**Issue by lilserf** [bra1n/townsquare#81]
**Is your feature request related to a problem? Please describe.**
The Vote History is a great resource but it's currently hard to tell which votes happened on which day, except for cases where the Majority value changed

**Describe the solution you'd like**
A clear way to separate the days from each other - a horizontal line, or a "Day #" column, or something similar

**Describe alternatives you've considered**
Anything that clearly shows which votes happened on the same day is good.

**Additional context**
None

**Comment by bra1n** [comment]
Hey @lilserf,
thanks for your suggestion! Unfortunately, there is no concept of "days" (or nights, for that matter) in the app. All the night toggle does is make a pretty background appear in everyone's browser. If, at some point, the game logic would become more involved in the app, it might make sense to enhance the vote history as well.
For now, I'd suggest you simply clear the history at the end of each day, for example. That way, it would also be cleared for your players and make the whole experience a bit more natural, because people now need to remember the votes from past days. ;-)

**Comment by JulGvoz** [comment]
Just as a possible temp fix of some sort, I think adding timestamps to the nominations would help (perhaps relative timestamps, for example "3 mins ago" or "11 mins ago"?)

Another possibility is just making a horizontal line whenever storyteller turns on the night mode - this could require just a bit of custom logic in the for loop looping over the nominations, where a special hard-coded nomination would be added for whenever ST switches to night.

**Comment by bra1n** [comment]
I'm not a big fan of keeping track of any night mode toggles, because it is not persisted at all at the moment and this would add quite a bit of complexity to a (currently) very simple feature. I do like showing a timestamp for each nomination though! I wouldn't make it relative though, because then you need to use an additional library to get this formatting. Just HH:mm should be fine, no?

**Comment by lilserf** [comment]
I can’t believe I spaced on the fact that the app, of course, has no knowledge of the days 😆
A timestamp would probably help tell the cycles apart, though.

**Comment by bra1n** [comment]
Will be fixed with #83 in the form of showing a timestamp for each finished vote :-)
