### ISSUE TITLE
Screenshots not working on Firefox

### ISSUE THREAD

**Issue by daalta** [bra1n/townsquare#9]
As mentioned in https://github.com/bra1n/townsquare/issues/6 , screenshots do not work when using Firefox.

... Though maybe it'd be fine if you only supported Chrome. Switching browsers isn't too difficult :)

**Comment by bra1n** [comment]
Added to the todo list. :-D It's not super high priority though.

**Comment by daalta** [comment]
Agreed!

**Comment by bra1n** [comment]
https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/clipboard/setImageData should contain the solution

**Comment by bra1n** [comment]
Alright, I looked into this some more and it turns out, that Firefox currently doesn't support adding screenshots directly to the clipboard. However, there's a built-in screenshot functionality in the browser that does an almost equally decent job, so I'd suggest you use that in the meantime, or switch to Chrome. ;-)

**Comment by daalta** [comment]
Good solution! Hiding makes sense, and mainly supporting Chrome does too.
