### ISSUE TITLE
Bug: ids in roles.json do not match ids given by official script making tool

### ISSUE THREAD

**Issue by JulGvoz** [bra1n/townsquare#99]
**Describe the bug**
Comparing the script making tool on https://bloodontheclocktower.com/script/ and the roles.json ids, it is clear that some of the ids do not match.

Examples:

- "id": "bounty_hunter" and "id": "bountyhunter"
- "id": "town_crier" and "id": "towncrier"

**Expected behavior**
I suggest adding underscores in ids where they are missing, for consistency.

**Comment by bra1n** [comment]
This is not a bug, all official script tool role IDs are compatible with my internally used IDs, because I strip out all non-alphanumeric characters when loading custom scripts: https://github.com/bra1n/townsquare/blob/main/src/components/modals/EditionModal.vue#L167
The role IDs are used in a few places, like the icon file name, the CSS class and more, where having special characters could be problematic. It also eliminates potential sources of mistakes like "pit-hag" vs. "pit hag" vs. "pithag"...

**Comment by CreativeMod1** [comment]
> This is not a bug, all official script tool role IDs are compatible with my internally used IDs, because I strip out all non-alphanumeric characters when loading custom scripts: https://github.com/bra1n/townsquare/blob/main/src/components/modals/EditionModal.vue#L167
> The role IDs are used in a few places, like the icon file name, the CSS class and more, where having special characters could be problematic. It also eliminates potential sources of mistakes like "pit-hag" vs. "pit hag" vs. "pithag"...

I've recently noticed that this isn't quite the case when it comes to copying over a gamestate json, if you're inputting a gamestate you must input it as towncrier rather than town_crier otherwise it shows an empty token. Not too much of an issue but just something I found

**Comment by bra1n** [comment]
> I've recently noticed that this isn't quite the case when it comes to copying over a gamestate json, if you're inputting a gamestate you must input it as towncrier rather than town_crier otherwise it shows an empty token. Not too much of an issue but just something I found

The app gamestate uses the internal IDs from the roles.json, true, and thus is not directly compatible with the official IDs. I guess I could also apply the transformation to gamestate JSON.
